# Generated by Django 5.2.6 on 2025-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActExtracurricular',
            fields=[
                ('id_act_extracurricular', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_act_extracurricular', models.CharField(max_length=100)),
                ('destino_act_extracurricular', models.CharField(max_length=45)),
                ('descripcion_act_extracurricular', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'act_extracurriculares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActExtracurricularXGrado',
            fields=[
                ('id_act_extracurricular_x_grado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_actividad', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField()),
            ],
            options={
                'db_table': 'act_extracurriculares_x_grados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_llegada_asistencia', models.DateTimeField()),
                ('estado_asistencia', models.CharField(choices=[('SÍ', 'Sí'), ('NO', 'No'), ('SE RETIRÓ', 'Se retiró')], default='no', max_length=10)),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_incidencia', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'incidencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lugares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedidaXAlumno',
            fields=[
                ('id_medida_x_alumno', models.AutoField(db_column='medida_alumno', primary_key=True, serialize=False)),
                ('fecha_medida', models.DateField(auto_now_add=True)),
                ('cantidad_dias', models.IntegerField(default=0)),
                ('descripcion_caso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medidas_x_alumnos',
                'ordering': ['-fecha_medida'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_reunion', models.DateTimeField()),
                ('tipo_reunion', models.CharField(choices=[('REUNIÓN INDIVIDUAL', 'Reunion Individual'), ('REUNIÓN GENERAL PADRES', 'Reunion General Padres'), ('REUNIÓN BILATERAL PADRES', 'Reunion Bilateral Padres')], default='reunion general padres', max_length=30)),
                ('descripcion_reunion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reuniones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id_tipo_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_incidencia_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_incidencia',
                'managed': False,
            },
        ),
    ]
