# Generated by Django 5.2.6 on 2025-10-26 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('dni_empleado', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI solo puede contener dígitos.', regex='^[0-9]+$')])),
                ('nombre_empleado', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')])),
                ('apellido_empleado', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')])),
                ('telefono_empleado', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números.', regex='^\\d*$')])),
                ('genero_empleado', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_empleado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('correo_empleado', models.CharField(max_length=45)),
                ('primer_login', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['apellido_empleado', 'nombre_empleado'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
    ]
