# Generated by Django 5.2.6 on 2025-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoXGrado',
            fields=[
                ('id_alumno_x_grado', models.AutoField(db_column='id_alumno_x_grado', primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, db_column='fecha_inscripcion')),
                ('activo', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'alumnos_x_grados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoXTutor',
            fields=[
                ('id_alumno_x_tutor', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alumno_x_tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colegios_procedencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_colegio_procedencia', models.IntegerField(blank=True, null=True, unique=True)),
                ('nombre_colegio_procedencia', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'colegios_procedencia',
                'ordering': ['nombre_colegio_procedencia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50)),
                ('asientos_disponibles', models.IntegerField()),
            ],
            options={
                'db_table': 'grados',
                'ordering': ['nombre_grado'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'parentescos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('dni_alumno', models.IntegerField(unique=True)),
                ('nombre_alumno', models.CharField(max_length=35)),
                ('apellido_alumno', models.CharField(max_length=35)),
                ('fecha_nacimiento_alumno', models.DateField()),
                ('genero_alumno', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('observaciones_alumno', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_alumno', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'alumnos',
                'ordering': ['apellido_alumno', 'nombre_alumno'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('dni_tutor', models.IntegerField(unique=True)),
                ('nombre_tutor', models.CharField(max_length=35)),
                ('apellido_tutor', models.CharField(max_length=35)),
                ('telefono_tutor', models.CharField(max_length=15)),
                ('correo_tutor', models.EmailField(max_length=100, unique=True)),
                ('genero_tutor', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('estado_tutor', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('primer_login', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tutores',
                'ordering': ['apellido_tutor', 'nombre_tutor'],
                'managed': True,
            },
        ),
    ]
